### ISSUE TITLE
`npm install -g clusternator` is broken

### ISSUE THREAD

**Issue by SethDavenport** [rangle/the-clusternator#197]
It's also out of date. We need to publish a new version.

Bugged @yuri to give Michael the access he needs to publish again.

**Comment by SethDavenport** [comment]
```
> clusternator@0.1.15 build /Users/sdavenpo/.npm/lib/node_modules/clusternator
> gulp transpile

module.js:327
    throw err;
    ^

Error: Cannot find module 'gulp-callback'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/sdavenpo/.npm/lib/node_modules/clusternator/gulpfile.js:4:15)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

**Comment by bennett000** [comment]
I have working npm permissions now.

**Comment by bennett000** [comment]
The current version on npm (`0.1.17`) builds/installs cleanly in an empty Ubuntu 14.04 container with node `4.2.4`.
