### ISSUE TITLE
Get unit tests to actually run

### ISSUE THREAD

**Issue by SethDavenport** [rangle/the-clusternator#235]
We have tests, they don't run.  I turned on CI. Make them run.

```
> clusternator@0.2.3 test /Users/sdavenpo/code/rangle/the-clusternator
> gulp test-unit

[17:25:26] Using gulpfile ~/code/rangle/the-clusternator/gulpfile.js
[17:25:26] Starting 'lint'...
[17:25:26] Starting 'pre-test-unit'...
[17:25:27] Finished 'pre-test-unit' after 1.31 s
[17:25:27] Finished 'lint' after 1.56 s
[17:25:27] Starting 'test-unit'...

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Cannot find module '../../src/api/0.1/project-fs/fs'
    at Function.Module._resolveFilename (module.js:325:15)
    at internalRewire (/Users/sdavenpo/code/rangle/the-clusternator/node_modules/rewire/lib/rewire.js:23:25)
    at rewire (/Users/sdavenpo/code/rangle/the-clusternator/node_modules/rewire/lib/index.js:11:12)
    at Object.<anonymous> (/Users/sdavenpo/code/rangle/the-clusternator/spec/unit/clusternator-json.spec.js:8:8)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/Users/sdavenpo/code/rangle/the-clusternator/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
npm ERR! Test failed.  See above for more details.
```

**Comment by SethDavenport** [comment]
Duplicate of #234
