### ISSUE TITLE
Handle connection error on init

### ISSUE THREAD

**Issue by rafkhan** [rangle/the-clusternator#243]
```
? Project ID project-augury
? Where should clusternator keep its files? .clusternator
? Where should clusternator keep your project's private files? asd
? What Top Level Domain (TLD) Will This Be Served From? rangleapp.io
? Choose a backend static
? Where will your appDefs/deployment files live? asd/deployments
? Will you be using CircleCI? Yes
? Please specify an external (public) port 80
? Please specify an internal (container/docker) port 80
? Please specify a protocol tcp
? Add more port mappings? No

info: Clusternator: Initialization Error: socket hang up
info: Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1032:19)
    at TLSSocket.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at TLSSocket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:903:12)
    at doNTCallback2 (node.js:439:9)
    at process._tickDomainCallback (node.js:394:17)
```

**Comment by bennett000** [comment]
@rafkhan do you have configuration details from your `~/.clusternator-config.json` ? Or other info on what caused the socket hangup? Like no internet connection?

With that info we can determine if there's a way we can handle this with a successful outcome, or just fail more gracefully.

To be fully robust we should really just specify the options as JSON.  They're currently a pretty plain object, all primitives except the ports array I believe.  We could load them with a `clusternator init -f /path/to/options`
