### ISSUE TITLE
Clusternator searches for git HEAD needlessly

### ISSUE THREAD

**Issue by rafkhan** [rangle/the-clusternator#262]
...and if there are no commits, it fails

```
$ clusternator deploy -d master

/Users/rafy/.nvm/versions/node/v4.2.1/lib/node_modules/clusternator/node_modules/q/q.js:155
                throw e;
                ^

Error: git rev-parse HEAD terminated with exit code: 128 fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

    at failError (/Users/rafy/.nvm/versions/node/v4.2.1/lib/node_modules/clusternator/lib/cli-wrappers/child-process.js:70:11)
    at ChildProcess.<anonymous> (/Users/rafy/.nvm/versions/node/v4.2.1/lib/node_modules/clusternator/lib/cli-wrappers/child-process.js:107:16)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

**Comment by bennett000** [comment]
This has been fixed, but it will need to be verified
