### ISSUE TITLE
Clusternator SSH breaks

### ISSUE THREAD

**Issue by rafkhan** [rangle/the-clusternator#325]

**Comment by rafkhan** [comment]
```
➜  the-clusternator git:(list-projects-rest) clusternator ssh
error: Error connecting with SSH.: Error: instances.map is not a function
    at Request._callback (/Users/rafy/.nvm/versions/node/v4.2.1/lib/node_modules/clusternator/lib/clusternator/common.js:235:16)
    at Request.self.callback (/Users/rafy/.nvm/versions/node/v4.2.1/lib/node_modules/clusternator/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/rafy/.nvm/versions/node/v4.2.1/lib/node_modules/clusternator/node_modules/request/request.js:1036:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Users/rafy/.nvm/versions/node/v4.2.1/lib/node_modules/clusternator/node_modules/request/request.js:963:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
```

**Comment by bennett000** [comment]
I did not get that break yet, but I did get a break wrt to SSH keys not working, in that they're seemingly not being installed.  We'll need to investigate.  I might do a re-deploy of the server we're using now to see if the keys work from the API... which I believe the currently do.

**Comment by bennett000** [comment]
ssh _does_ work on my end but the PR/Deployment through Circle is not working
