### ISSUE TITLE
Deployment Command Breaks Using AWS

### ISSUE THREAD

**Issue by bennett000** [rangle/the-clusternator#331]
This is with 0.5.1 using AWS credentials to do the deploy.  The AWS `projectManager.createDeployment` works from the REPL so the error must be in data not being forwarded from the client/CLI code
```
error: Failed to deploy the-clusternator:master TypeError: Cannot read property 'map' of undefined
    at /Users/michael/Workspaces/rangle/the-clusternator/node_modules/ramda/dist/ramda.js:3911:31
    at Object.f2 [as map] (/Users/michael/Workspaces/rangle/the-clusternator/node_modules/ramda/dist/ramda.js:191:24)
    at Object.createTasksAndServicesOnCluster [as create] (/Users/michael/Workspaces/rangle/the-clusternator/lib/aws/taskServiceManager.js:198:29)
    at Object.createTask (/Users/michael/Workspaces/rangle/the-clusternator/lib/aws/common.js:398:15)
    at /Users/michael/Workspaces/rangle/the-clusternator/lib/aws/deploymentManager.js:98:21
    at _fulfilled (/Users/michael/Workspaces/rangle/the-clusternator/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/michael/Workspaces/rangle/the-clusternator/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/michael/Workspaces/rangle/the-clusternator/node_modules/q/q.js:796:13)
    at /Users/michael/Workspaces/rangle/the-clusternator/node_modules/q/q.js:604:44
    at runSingle (/Users/michael/Workspaces/rangle/the-clusternator/node_modules/q/q.js:137:13)
```

**Comment by rafkhan** [comment]
This has been fixed

**Comment by rafkhan** [comment]
@bennett000 moving to done
