### ISSUE TITLE
`clusternator init` tries to create user every time, fails

### ISSUE THREAD

**Issue by rafkhan** [rangle/the-clusternator#339]

**Comment by rafkhan** [comment]
```
clusternator init                                                                                                 Mon  4 Apr 2016 10:31:48 EDT
? Project ID matt-test
? GitHub username of "master"/main/central repo rangle
? Where should clusternator keep its files? .clusternator
? Where should clusternator keep your project's private files? .private
? What Top Level Domain (TLD) Will This Be Served From? rangleapp.io
? Choose a backend static
? Where will your appDefs/deployment files live? .private/deployments
? Would you like git hooks installed that will encrypt/decrypt your .private files before/after commit, and after pulls? Yes
? Will you be using CircleCI? Yes
? Please specify an external (public) port 80
? Please specify an internal (container/docker) port 80
? Please specify a protocol tcp
? Add more port mappings? No
info: proceeding with matt-test
info: Clusternator: Initialization Error: createUser: User Exists
info: Error: createUser: User Exists
    at Request._callback (/usr/local/lib/node_modules/clusternator/lib/clusternator/common.js:235:16)
    at Request.self.callback (/usr/local/lib/node_modules/clusternator/node_modules/request/request.js:199:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/clusternator/node_modules/request/request.js:1036:10)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/clusternator/node_modules/request/request.js:963:12)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
```

**Comment by rafkhan** [comment]
@bennett000 :(

**Comment by bennett000** [comment]
This should hopefully be easy to fix.  Each clusternator project gets its own user account which is used for authenticating/authorizing project level requests, like from Circle or GitHub...

In theory (haven't checked source) the server should be able to work with the existing user, but obviously that's not happening.

@rafkhan has this project been initialized before?

**Comment by mattmcfad** [comment]
@bennett000 yes, this was on a project that had been initialized before

**Comment by bennett000** [comment]
@mattmcfad @rafkhan told me he would work on this after he finished his current problem.  It should be a relatively easy fix.  If you want to tackle it just let @rafkhan know.  

You would have been working in a similar space for the slack channel issues
