### ISSUE TITLE
Error on Clusternator init

### ISSUE THREAD

**Issue by SethDavenport** [rangle/the-clusternator#368]
This has happened twice today:

```sh
dclust init                                                                                                        Tue 12 Apr 2016 21:40:34 EDT
? Project ID angular2-starter
? GitHub username of "master"/main/central repo rangle
? Where should clusternator keep its files? .clusternator
? Where should clusternator keep your project's private files? .private
? What Top Level Domain (TLD) Will This Be Served From? rangleapp.io
? Choose a backend node (long-term-support)
? Where will your appDefs/deployment files live? .private/deployments
? Would you like git hooks installed that will encrypt/decrypt your .private files before/after commit, and after pulls? No
? Will you be using CircleCI? Yes
? Please specify an external (public) port 80
? Please specify an internal (container/docker) port 3000
? Please specify a protocol tcp
? Add more port mappings? No
info: proceeding with angular2-starter
info: Clusternator: Private files/directories encrypted
info: Clusternator: Private files un-encrypted
info: Generated shasum of .private => 8326e304429fab365659dd20bab051b2d7646b7b
info: Clusternator: Initialization Error: The subnet ID 'subnet-b8c74c92' does not exist
info: Error: The subnet ID 'subnet-b8c74c92' does not exist
    at Request._callback (/Users/sdavenpo/code/rangle/the-clusternator/lib/clusternator/common.js:235:16)
    at Request.self.callback (/Users/sdavenpo/code/rangle/the-clusternator/node_modules/request/request.js:199:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/Users/sdavenpo/code/rangle/the-clusternator/node_modules/request/request.js:1036:10)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/Users/sdavenpo/code/rangle/the-clusternator/node_modules/request/request.js:963:12)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
```

When I tried again I got a new error about a subnet CIDR conflict.

I went into AWS and deleted the existing subnet and tried a third time and it worked.

**Comment by SethDavenport** [comment]
Sounds like the VPC functions need to be made idempotent and retryable like the newer AWS code.

**Comment by bennett000** [comment]
There's now a PR out there that makes the VPC functions idempotent and maintainable.  This unfortunately does _not_ upgrade _all_ the subnet code.  The VPC integration _did_ fix one of the subnet's edge cases though, but seemingly a different one than this.
